version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
      
  web: &app_base
    build: .
    stdin_open: true
    tty: true
    command: bash -c "bundle exec puma -C config/puma.rb"
    environment:
      RAILS_ENV: $RAILS_ENV
      NODE_ENV: $RAILS_ENV
      BUNDLE_APP_CONFIG: ./.bundle
    volumes:
      - .:/kd_world
      - bundle:/kd_world/vendor/bundle
      - node-modules:/kd_world/node_modules
      - packs:/kd_world/public/packs
    ports:
      - $HTTP_PORT:3000
    depends_on:
      - db

  webpack:
    <<: *app_base
    command: /bin/sh -c "bin/webpack-dev-server --config webpack.config.js"
    environment:
      NODE_ENV: $RAILS_ENV
      RAILS_ENV: $RAILS_ENV
      BUNDLE_APP_CONFIG: ./.bundle
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - $WEBPACK_PORT:3035
    tty: true
    stdin_open: true
    depends_on:
      - web
    volumes:
      - .:/kd_world
      - packs:/kd_world/public/packs

volumes:
  bundle:
  node-modules:
  packs:
